/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Prototipo.java
 *
 * Created on 21/10/2009, 22:17:10
 */
package busca;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FilenameFilter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author fabricio
 */
public class BuscaArquivos extends javax.swing.JFrame {

    /** Creates new form Prototipo */
    public BuscaArquivos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpExtensao = new javax.swing.ButtonGroup();
        lblTexto = new javax.swing.JLabel();
        txtTexto = new javax.swing.JTextField();
        pnlLocalConsulta = new javax.swing.JPanel();
        rdbLog = new javax.swing.JRadioButton();
        rdbTxt = new javax.swing.JRadioButton();
        btnProcurar = new javax.swing.JButton();
        pnlArquivosEncontrados = new javax.swing.JPanel();
        srcArquivos = new javax.swing.JScrollPane();
        lstArquivos = new javax.swing.JList();
        srcConteudo = new javax.swing.JScrollPane();
        txaConteudo = new javax.swing.JTextArea();
        txtLocal = new javax.swing.JTextField();
        lblLocal = new javax.swing.JLabel();
        btnLocal = new javax.swing.JButton();
        pnlLocalConsulta1 = new javax.swing.JPanel();
        chkConteudo = new javax.swing.JCheckBox();
        chkNomeArquivo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busca Arquivos");
        getContentPane().setLayout(null);

        lblTexto.setText("Texto");
        getContentPane().add(lblTexto);
        lblTexto.setBounds(10, 50, 36, 16);
        getContentPane().add(txtTexto);
        txtTexto.setBounds(60, 50, 320, 28);

        pnlLocalConsulta.setBorder(javax.swing.BorderFactory.createTitledBorder("Extencao:"));
        pnlLocalConsulta.setLayout(null);

        grpExtensao.add(rdbLog);
        rdbLog.setText("log");
        pnlLocalConsulta.add(rdbLog);
        rdbLog.setBounds(110, 20, 60, 23);

        grpExtensao.add(rdbTxt);
        rdbTxt.setSelected(true);
        rdbTxt.setText("txt");
        pnlLocalConsulta.add(rdbTxt);
        rdbTxt.setBounds(20, 20, 50, 23);

        getContentPane().add(pnlLocalConsulta);
        pnlLocalConsulta.setBounds(290, 90, 200, 50);

        btnProcurar.setText("Procurar");
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcurar);
        btnProcurar.setBounds(390, 50, 90, 29);

        pnlArquivosEncontrados.setBorder(javax.swing.BorderFactory.createTitledBorder("Arquivos encontrados:"));
        pnlArquivosEncontrados.setLayout(null);

        lstArquivos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstArquivosValueChanged(evt);
            }
        });
        srcArquivos.setViewportView(lstArquivos);

        pnlArquivosEncontrados.add(srcArquivos);
        srcArquivos.setBounds(10, 20, 190, 200);

        txaConteudo.setColumns(20);
        txaConteudo.setEditable(false);
        txaConteudo.setRows(5);
        srcConteudo.setViewportView(txaConteudo);

        pnlArquivosEncontrados.add(srcConteudo);
        srcConteudo.setBounds(210, 20, 260, 200);

        getContentPane().add(pnlArquivosEncontrados);
        pnlArquivosEncontrados.setBounds(10, 140, 480, 230);

        txtLocal.setEditable(false);
        getContentPane().add(txtLocal);
        txtLocal.setBounds(60, 10, 370, 28);

        lblLocal.setText("Local");
        getContentPane().add(lblLocal);
        lblLocal.setBounds(10, 10, 33, 16);

        btnLocal.setText("...");
        btnLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalActionPerformed(evt);
            }
        });
        getContentPane().add(btnLocal);
        btnLocal.setBounds(440, 10, 40, 30);

        pnlLocalConsulta1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar:"));
        pnlLocalConsulta1.setLayout(null);

        chkConteudo.setText("Conteudo");
        pnlLocalConsulta1.add(chkConteudo);
        chkConteudo.setBounds(10, 20, 100, 23);

        chkNomeArquivo.setSelected(true);
        chkNomeArquivo.setText("Nome do arquivo");
        pnlLocalConsulta1.add(chkNomeArquivo);
        chkNomeArquivo.setBounds(120, 20, 140, 23);

        getContentPane().add(pnlLocalConsulta1);
        pnlLocalConsulta1.setBounds(10, 90, 270, 50);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-506)/2, (screenSize.height-410)/2, 506, 410);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //Exibe o diálogo. Deve ser passado por parâmetro o JFrame de origem.
        fc.showOpenDialog(this);
        //Captura o objeto File que representa o arquivo selecionado.
        File file = fc.getSelectedFile();
        txtLocal.setText(file.getAbsolutePath());
}//GEN-LAST:event_btnLocalActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        String sFile = txtLocal.getText();
        if (sFile != null && sFile.trim().length() != 0) {
            List<String> arquivos = new ArrayList<String>();
            //Somente seleciona arquivos com extencao .txt
            File[] files = new File(sFile).listFiles(new FilenameFilter() {
                public boolean accept(File dir, String name) {
                    String extensao = "";
                    if(rdbTxt.isSelected()) {
                        extensao = "txt";
                    } else if(rdbLog.isSelected()) {
                        extensao = "log";
                    }

                    if (name.endsWith(extensao)) {
                        return true;
                    } else {
                        return false;
                    }
                }
            });
            String texto = txtTexto.getText();
            for (File f : files) {
                if (chkConteudo.isSelected() && getConteudo(f).contains(texto)) {
                    arquivos.add(f.getAbsolutePath());
                    continue;
                }
                if (chkNomeArquivo.isSelected() && f.getName().contains(texto)) {
                    arquivos.add(f.getAbsolutePath());
                    continue;
                }
            }
            lstArquivos.setListData(new Vector(arquivos));
        } else {
            JOptionPane.showMessageDialog(this, "Selecione o local de busca.");
        }
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void lstArquivosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstArquivosValueChanged
        if (lstArquivos.getSelectedValue() != null) {
            String arquivo = (String) lstArquivos.getSelectedValue();
            txaConteudo.setText(getConteudo(new File(arquivo)));
        }
    }//GEN-LAST:event_lstArquivosValueChanged

    private String getConteudo(File file) {
        FileReader fileReader = null;
        BufferedReader bufferedReader = null;
        try {
            fileReader = new FileReader(file.getAbsolutePath());
            bufferedReader = new BufferedReader(fileReader);
            StringBuilder sb = new StringBuilder();
            while (bufferedReader.ready()) {
                sb.append(bufferedReader.readLine());
                sb.append("\n");
            }

            return sb.toString();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao abrir o arquivo: " + ex.getMessage());
        } finally {
            if (bufferedReader != null) {
                try {
                    bufferedReader.close();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao abrir o arquivo: " + ex.getMessage());
                }
            }
            if (fileReader != null) {
                try {
                    fileReader.close();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao abrir o arquivo: " + ex.getMessage());
                }
            }
        }
        return "";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BuscaArquivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLocal;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JCheckBox chkConteudo;
    private javax.swing.JCheckBox chkNomeArquivo;
    private javax.swing.ButtonGroup grpExtensao;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JList lstArquivos;
    private javax.swing.JPanel pnlArquivosEncontrados;
    private javax.swing.JPanel pnlLocalConsulta;
    private javax.swing.JPanel pnlLocalConsulta1;
    private javax.swing.JRadioButton rdbLog;
    private javax.swing.JRadioButton rdbTxt;
    private javax.swing.JScrollPane srcArquivos;
    private javax.swing.JScrollPane srcConteudo;
    private javax.swing.JTextArea txaConteudo;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtTexto;
    // End of variables declaration//GEN-END:variables
}
